# Generated by Django 3.0.8 on 2020-10-12 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreq',
            name='foodtakenfrom',
            field=models.IntegerField(max_length=250),
        ),
        migrations.AlterField(
            model_name='foodreq',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', related_query_name='foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
