# Generated by Django 3.0.8 on 2020-10-12 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donate', '0003_auto_20201012_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreq',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', related_query_name='foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
