# Generated by Django 3.0.8 on 2020-10-16 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0005_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='ratings',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
