# Generated by Django 3.1 on 2020-10-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0013_foodavbl_edible'),
        ('Donate', '0006_auto_20201016_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('pickup_address', models.TextField(max_length=20)),
                ('O_ID', models.ManyToManyField(related_name='O_ID', to='NGO.foodAvbl')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_foods', related_query_name='order_foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
