# Generated by Django 3.1 on 2020-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0007_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='O_ID',
        ),
        migrations.AddField(
            model_name='orders',
            name='O_ID',
            field=models.IntegerField(default=0),
        ),
    ]
