# Generated by Django 3.1 on 2020-10-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0008_auto_20201016_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='s',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
