# Generated by Django 3.0.8 on 2020-10-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0009_orders_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='s',
            field=models.IntegerField(default=1),
        ),
    ]
