# Generated by Django 3.1 on 2020-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0010_auto_20201017_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pickup_address',
            field=models.TextField(max_length=200),
        ),
    ]
