# Generated by Django 3.0.8 on 2020-10-09 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0002_auto_20201006_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='belongs',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong', related_query_name='belong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='otherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=250)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.Cities')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', related_query_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
