# Generated by Django 3.0.8 on 2020-10-11 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0004_otherdetails_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='foodAvbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pickup_address', models.TextField(default='', max_length=20)),
                ('time_to_pickup_till', models.DateTimeField(null=True)),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.Measurement')),
                ('otherDetails', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.otherDetails')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodss', related_query_name='foodss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
