# Generated by Django 3.0.8 on 2020-10-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0005_foodavbl_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodavbl',
            name='time_to_pickup_till',
        ),
        migrations.AlterField(
            model_name='foodavbl',
            name='pickup_address',
            field=models.TextField(max_length=20),
        ),
    ]
