# Generated by Django 3.0.8 on 2020-10-11 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0006_auto_20201011_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodavbl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodss', related_query_name='foodss', to=settings.AUTH_USER_MODEL, unique='True'),
        ),
    ]
