# Generated by Django 3.0.8 on 2020-10-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0008_auto_20201011_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodavbl',
            name='city',
            field=models.CharField(default='enter', max_length=100),
        ),
    ]
