# Generated by Django 3.0.8 on 2020-10-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0010_foodavbl_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='image',
            field=models.ImageField(default='food12.jpeg', upload_to='NGO/images'),
        ),
    ]
