# Generated by Django 3.1 on 2020-10-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0012_auto_20201016_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodavbl',
            name='edible',
            field=models.IntegerField(default=0),
        ),
    ]
