# Generated by Django 3.0.8 on 2020-10-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0013_foodavbl_edible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodavbl',
            name='edible',
        ),
    ]
