# Generated by Django 3.1 on 2020-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0014_remove_foodavbl_edible'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodavbl',
            name='edible',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='phonenumber',
            field=models.IntegerField(default=9898944123),
        ),
    ]
