# Generated by Django 3.0.8 on 2020-10-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0016_auto_20201016_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodavbl',
            name='FoodKind',
        ),
        migrations.RemoveField(
            model_name='foodavbl',
            name='image',
        ),
        migrations.AddField(
            model_name='foodavbl',
            name='Other_Specifics',
            field=models.TextField(default='Punjabi,Chinese,Mexican', max_length=100),
        ),
        migrations.AddField(
            model_name='foodavbl',
            name='images',
            field=models.ImageField(default='/media/food12.jpeg', upload_to='NGO/images'),
        ),
        migrations.AlterField(
            model_name='foodavbl',
            name='typee',
            field=models.ForeignKey(default='veg', null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.TypeOf'),
        ),
        migrations.DeleteModel(
            name='options',
        ),
    ]
