# Generated by Django 3.1 on 2020-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0018_auto_20201016_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodavbl',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='NGO/images'),
        ),
    ]
